/**
 * Tarot Cards Seed Data
 * 塔罗牌种子数据
 */

import type { TarotCard } from '../../../shared/types/tarot';

// 大阿卡纳 (Major Arcana) - 22张
const majorArcanaCards: Omit<TarotCard, 'id'>[] = [
  {
    name_zh: '愚者',
    name_en: 'The Fool',
    suit: 'major',
    number: 0,
    image_url: '/images/tarot/major/fool.jpg',
    keywords_zh: '["新开始", "冒险", "纯真", "自由"]',
    keywords_en: '["New Beginnings", "Adventure", "Innocence", "Freedom"]',
    meaning_upright_zh: '新的开始，充满可能性的旅程，纯真的心灵，勇敢的冒险精神。',
    meaning_upright_en: 'New beginnings, a journey full of possibilities, innocent heart, brave adventurous spirit.',
    meaning_reversed_zh: '鲁莽行事，缺乏计划，过度天真，逃避责任。',
    meaning_reversed_en: 'Reckless behavior, lack of planning, excessive naivety, avoiding responsibility.',
    element: 'Air',
    astrological_sign: 'Uranus',
    planet: 'Uranus',
    description_zh: '愚者代表着新的开始和无限的可能性。他象征着纯真的心灵和勇敢的冒险精神，提醒我们要保持开放的心态去迎接生活中的新挑战。',
    description_en: 'The Fool represents new beginnings and infinite possibilities. He symbolizes an innocent heart and brave adventurous spirit, reminding us to keep an open mind to embrace new challenges in life.'
  },
  {
    name_zh: '魔术师',
    name_en: 'The Magician',
    suit: 'major',
    number: 1,
    image_url: '/images/tarot/major/magician.jpg',
    keywords_zh: '["意志力", "技能", "专注", "行动"]',
    keywords_en: '["Willpower", "Skill", "Focus", "Action"]',
    meaning_upright_zh: '拥有实现目标的能力，专注的意志力，技能和资源的运用，主动的行动。',
    meaning_upright_en: 'Ability to achieve goals, focused willpower, use of skills and resources, proactive action.',
    meaning_reversed_zh: '缺乏意志力，技能不足，滥用权力，欺骗他人。',
    meaning_reversed_en: 'Lack of willpower, insufficient skills, abuse of power, deceiving others.',
    element: 'Air',
    astrological_sign: 'Mercury',
    planet: 'Mercury',
    description_zh: '魔术师象征着意志力和实现目标的能力。他提醒我们拥有实现梦想所需的所有工具和技能，关键在于如何运用它们。',
    description_en: 'The Magician symbolizes willpower and the ability to achieve goals. He reminds us that we have all the tools and skills needed to realize our dreams, the key is how to use them.'
  },
  {
    name_zh: '女祭司',
    name_en: 'The High Priestess',
    suit: 'major',
    number: 2,
    image_url: '/images/tarot/major/high_priestess.jpg',
    keywords_zh: '["直觉", "神秘", "潜意识", "智慧"]',
    keywords_en: '["Intuition", "Mystery", "Subconscious", "Wisdom"]',
    meaning_upright_zh: '强大的直觉力，内在的智慧，神秘的知识，潜意识的洞察。',
    meaning_upright_en: 'Strong intuitive power, inner wisdom, mysterious knowledge, subconscious insight.',
    meaning_reversed_zh: '缺乏直觉，忽视内在声音，过度理性，隐藏真相。',
    meaning_reversed_en: 'Lack of intuition, ignoring inner voice, excessive rationality, hiding truth.',
    element: 'Water',
    astrological_sign: 'Moon',
    planet: 'Moon',
    description_zh: '女祭司代表着直觉和内在智慧。她提醒我们要倾听内心的声音，相信自己的直觉，从潜意识中获取指引。',
    description_en: 'The High Priestess represents intuition and inner wisdom. She reminds us to listen to our inner voice, trust our intuition, and seek guidance from the subconscious.'
  },
  {
    name_zh: '皇后',
    name_en: 'The Empress',
    suit: 'major',
    number: 3,
    image_url: '/images/tarot/major/empress.jpg',
    keywords_zh: '["丰盛", "母性", "创造力", "自然"]',
    keywords_en: '["Abundance", "Motherhood", "Creativity", "Nature"]',
    meaning_upright_zh: '丰盛和富足，母性的关怀，创造力的表达，与自然的连接。',
    meaning_upright_en: 'Abundance and prosperity, maternal care, expression of creativity, connection with nature.',
    meaning_reversed_zh: '创造力受阻，过度依赖，缺乏自信，忽视自我需求。',
    meaning_reversed_en: 'Blocked creativity, excessive dependence, lack of confidence, neglecting self-needs.',
    element: 'Earth',
    astrological_sign: 'Venus',
    planet: 'Venus',
    description_zh: '皇后象征着丰盛、创造力和母性的力量。她提醒我们要珍惜生活中的美好，发挥自己的创造力，关爱他人和自己。',
    description_en: 'The Empress symbolizes abundance, creativity, and maternal power. She reminds us to cherish the beauty in life, express our creativity, and care for others and ourselves.'
  },
  {
    name_zh: '皇帝',
    name_en: 'The Emperor',
    suit: 'major',
    number: 4,
    image_url: '/images/tarot/major/emperor.jpg',
    keywords_zh: '["权威", "秩序", "领导力", "稳定"]',
    keywords_en: '["Authority", "Order", "Leadership", "Stability"]',
    meaning_upright_zh: '强大的领导力，秩序和结构，权威和稳定，目标导向的行动。',
    meaning_upright_en: 'Strong leadership, order and structure, authority and stability, goal-oriented action.',
    meaning_reversed_zh: '过度控制，缺乏灵活性，滥用权威，独裁倾向。',
    meaning_reversed_en: 'Excessive control, lack of flexibility, abuse of authority, dictatorial tendencies.',
    element: 'Fire',
    astrological_sign: 'Aries',
    planet: 'Mars',
    description_zh: '皇帝代表着权威、领导力和秩序。他提醒我们要承担责任，建立稳定的基础，以理性和目标为导向来管理生活。',
    description_en: 'The Emperor represents authority, leadership, and order. He reminds us to take responsibility, build stable foundations, and manage life with rationality and goal orientation.'
  },
  {
    name_zh: '教皇',
    name_en: 'The Hierophant',
    suit: 'major',
    number: 5,
    image_url: '/images/tarot/major/hierophant.jpg',
    keywords_zh: '["传统", "教育", "精神指导", "仪式"]',
    keywords_en: '["Tradition", "Education", "Spiritual Guidance", "Ritual"]',
    meaning_upright_zh: '传统价值观，精神指导，教育和学习，仪式和信仰。',
    meaning_upright_en: 'Traditional values, spiritual guidance, education and learning, ritual and faith.',
    meaning_reversed_zh: '过度传统，缺乏独立思考，教条主义，反叛权威。',
    meaning_reversed_en: 'Excessive tradition, lack of independent thinking, dogmatism, rebellion against authority.',
    element: 'Earth',
    astrological_sign: 'Taurus',
    planet: 'Venus',
    description_zh: '教皇象征着传统、教育和精神指导。他提醒我们要尊重传统，寻求精神指导，通过学习和仪式来成长。',
    description_en: 'The Hierophant symbolizes tradition, education, and spiritual guidance. He reminds us to respect tradition, seek spiritual guidance, and grow through learning and ritual.'
  },
  {
    name_zh: '恋人',
    name_en: 'The Lovers',
    suit: 'major',
    number: 6,
    image_url: '/images/tarot/major/lovers.jpg',
    keywords_zh: '["爱情", "选择", "和谐", "结合"]',
    keywords_en: '["Love", "Choice", "Harmony", "Union"]',
    meaning_upright_zh: '深刻的爱情，重要的选择，和谐的关系，精神与肉体的结合。',
    meaning_upright_en: 'Deep love, important choices, harmonious relationships, union of spirit and body.',
    meaning_reversed_zh: '关系不和谐，错误的选择，缺乏承诺，价值观冲突。',
    meaning_reversed_en: 'Unharmonious relationships, wrong choices, lack of commitment, value conflicts.',
    element: 'Air',
    astrological_sign: 'Gemini',
    planet: 'Mercury',
    description_zh: '恋人代表着爱情、选择和和谐的关系。他提醒我们要做出正确的选择，珍惜真爱，在关系中保持平衡和和谐。',
    description_en: 'The Lovers represent love, choice, and harmonious relationships. He reminds us to make the right choices, cherish true love, and maintain balance and harmony in relationships.'
  },
  {
    name_zh: '战车',
    name_en: 'The Chariot',
    suit: 'major',
    number: 7,
    image_url: '/images/tarot/major/chariot.jpg',
    keywords_zh: '["意志力", "胜利", "控制", "决心"]',
    keywords_en: '["Willpower", "Victory", "Control", "Determination"]',
    meaning_upright_zh: '强大的意志力，胜利和成功，自我控制，坚定的决心。',
    meaning_upright_en: 'Strong willpower, victory and success, self-control, firm determination.',
    meaning_reversed_zh: '缺乏控制，方向不明，意志力薄弱，过度自信。',
    meaning_reversed_en: 'Lack of control, unclear direction, weak willpower, excessive confidence.',
    element: 'Water',
    astrological_sign: 'Cancer',
    planet: 'Moon',
    description_zh: '战车象征着意志力和胜利。他提醒我们要保持坚定的决心，控制自己的情绪和冲动，朝着目标前进。',
    description_en: 'The Chariot symbolizes willpower and victory. He reminds us to maintain firm determination, control our emotions and impulses, and move forward toward our goals.'
  },
  {
    name_zh: '力量',
    name_en: 'Strength',
    suit: 'major',
    number: 8,
    image_url: '/images/tarot/major/strength.jpg',
    keywords_zh: '["内在力量", "勇气", "耐心", "温柔"]',
    keywords_en: '["Inner Strength", "Courage", "Patience", "Gentleness"]',
    meaning_upright_zh: '内在的力量，勇气和耐心，温柔的控制，精神的力量。',
    meaning_upright_en: 'Inner strength, courage and patience, gentle control, spiritual power.',
    meaning_reversed_zh: '缺乏自信，过度控制，内心脆弱，滥用力量。',
    meaning_reversed_en: 'Lack of confidence, excessive control, inner fragility, abuse of power.',
    element: 'Fire',
    astrological_sign: 'Leo',
    planet: 'Sun',
    description_zh: '力量代表着内在的力量和勇气。她提醒我们真正的力量来自于内心，通过温柔和耐心来克服困难。',
    description_en: 'Strength represents inner strength and courage. She reminds us that true strength comes from within, overcoming difficulties through gentleness and patience.'
  },
  {
    name_zh: '隐者',
    name_en: 'The Hermit',
    suit: 'major',
    number: 9,
    image_url: '/images/tarot/major/hermit.jpg',
    keywords_zh: '["内省", "智慧", "孤独", "指引"]',
    keywords_en: '["Introspection", "Wisdom", "Solitude", "Guidance"]',
    meaning_upright_zh: '内省和反思，寻求内在智慧，孤独中的成长，为他人提供指引。',
    meaning_upright_en: 'Introspection and reflection, seeking inner wisdom, growth in solitude, providing guidance for others.',
    meaning_reversed_zh: '过度孤独，缺乏指引，迷失方向，拒绝帮助。',
    meaning_reversed_en: 'Excessive loneliness, lack of guidance, lost direction, refusing help.',
    element: 'Earth',
    astrological_sign: 'Virgo',
    planet: 'Mercury',
    description_zh: '隐者象征着内省和智慧。他提醒我们要在孤独中寻找内在的智慧，通过反思来成长，并为他人提供指引。',
    description_en: 'The Hermit symbolizes introspection and wisdom. He reminds us to seek inner wisdom in solitude, grow through reflection, and provide guidance for others.'
  },
  {
    name_zh: '命运之轮',
    name_en: 'Wheel of Fortune',
    suit: 'major',
    number: 10,
    image_url: '/images/tarot/major/wheel_of_fortune.jpg',
    keywords_zh: '["命运", "变化", "循环", "机遇"]',
    keywords_en: '["Destiny", "Change", "Cycle", "Opportunity"]',
    meaning_upright_zh: '命运的变化，新的机遇，生活的循环，积极的变化。',
    meaning_upright_en: 'Changes in destiny, new opportunities, life cycles, positive changes.',
    meaning_reversed_zh: '消极的变化，错失机遇，命运不济，缺乏控制。',
    meaning_reversed_en: 'Negative changes, missed opportunities, bad luck, lack of control.',
    element: 'Fire',
    astrological_sign: 'Jupiter',
    planet: 'Jupiter',
    description_zh: '命运之轮象征着生活的变化和循环。他提醒我们生活是不断变化的，要抓住机遇，接受变化，相信命运的安排。',
    description_en: 'The Wheel of Fortune symbolizes the changes and cycles of life. He reminds us that life is constantly changing, to seize opportunities, accept changes, and trust in destiny.'
  },
  {
    name_zh: '正义',
    name_en: 'Justice',
    suit: 'major',
    number: 11,
    image_url: '/images/tarot/major/justice.jpg',
    keywords_zh: '["公正", "平衡", "真理", "责任"]',
    keywords_en: '["Fairness", "Balance", "Truth", "Responsibility"]',
    meaning_upright_zh: '公正和平衡，真理和正义，承担责任，因果报应。',
    meaning_upright_en: 'Fairness and balance, truth and justice, taking responsibility, karma.',
    meaning_reversed_zh: '不公正，缺乏平衡，逃避责任，偏见和歧视。',
    meaning_reversed_en: 'Injustice, lack of balance, avoiding responsibility, prejudice and discrimination.',
    element: 'Air',
    astrological_sign: 'Libra',
    planet: 'Venus',
    description_zh: '正义象征着公正和平衡。她提醒我们要追求真理和正义，承担自己的责任，保持内心的平衡。',
    description_en: 'Justice symbolizes fairness and balance. She reminds us to pursue truth and justice, take responsibility for our actions, and maintain inner balance.'
  },
  {
    name_zh: '倒吊人',
    name_en: 'The Hanged Man',
    suit: 'major',
    number: 12,
    image_url: '/images/tarot/major/hanged_man.jpg',
    keywords_zh: '["牺牲", "等待", "新视角", "精神成长"]',
    keywords_en: '["Sacrifice", "Waiting", "New Perspective", "Spiritual Growth"]',
    meaning_upright_zh: '必要的牺牲，耐心等待，新的视角，精神上的成长。',
    meaning_upright_en: 'Necessary sacrifice, patient waiting, new perspective, spiritual growth.',
    meaning_reversed_zh: '无意义的牺牲，过度等待，拒绝改变，停滞不前。',
    meaning_reversed_en: 'Meaningless sacrifice, excessive waiting, refusing to change, stagnation.',
    element: 'Water',
    astrological_sign: 'Neptune',
    planet: 'Neptune',
    description_zh: '倒吊人象征着牺牲和等待。他提醒我们有时候需要牺牲和等待，从不同的角度看待问题，在精神上获得成长。',
    description_en: 'The Hanged Man symbolizes sacrifice and waiting. He reminds us that sometimes we need to sacrifice and wait, look at problems from different angles, and grow spiritually.'
  },
  {
    name_zh: '死神',
    name_en: 'Death',
    suit: 'major',
    number: 13,
    image_url: '/images/tarot/major/death.jpg',
    keywords_zh: '["结束", "转变", "重生", "释放"]',
    keywords_en: '["End", "Transformation", "Rebirth", "Release"]',
    meaning_upright_zh: '旧事物的结束，新的开始，深刻的转变，重生的机会。',
    meaning_upright_en: 'End of old things, new beginnings, profound transformation, opportunity for rebirth.',
    meaning_reversed_zh: '拒绝改变，恐惧结束，停滞不前，无法释放过去。',
    meaning_reversed_en: 'Refusing to change, fear of endings, stagnation, unable to let go of the past.',
    element: 'Water',
    astrological_sign: 'Scorpio',
    planet: 'Pluto',
    description_zh: '死神象征着结束和转变。他提醒我们结束是新的开始，要勇敢地面对变化，释放过去，迎接重生。',
    description_en: 'Death symbolizes endings and transformation. He reminds us that endings are new beginnings, to bravely face changes, release the past, and welcome rebirth.'
  },
  {
    name_zh: '节制',
    name_en: 'Temperance',
    suit: 'major',
    number: 14,
    image_url: '/images/tarot/major/temperance.jpg',
    keywords_zh: '["平衡", "调和", "耐心", "和谐"]',
    keywords_en: '["Balance", "Harmony", "Patience", "Moderation"]',
    meaning_upright_zh: '内在的平衡，调和不同的元素，耐心和节制，和谐的生活。',
    meaning_upright_en: 'Inner balance, harmonizing different elements, patience and moderation, harmonious life.',
    meaning_reversed_zh: '缺乏平衡，过度极端，急躁不安，内心冲突。',
    meaning_reversed_en: 'Lack of balance, excessive extremes, restlessness, inner conflict.',
    element: 'Fire',
    astrological_sign: 'Sagittarius',
    planet: 'Jupiter',
    description_zh: '节制象征着平衡和调和。她提醒我们要在生活中保持平衡，调和不同的元素，通过耐心和节制来达到和谐。',
    description_en: 'Temperance symbolizes balance and harmony. She reminds us to maintain balance in life, harmonize different elements, and achieve harmony through patience and moderation.'
  },
  {
    name_zh: '恶魔',
    name_en: 'The Devil',
    suit: 'major',
    number: 15,
    image_url: '/images/tarot/major/devil.jpg',
    keywords_zh: '["束缚", "诱惑", "恐惧", "物质主义"]',
    keywords_en: '["Bondage", "Temptation", "Fear", "Materialism"]',
    meaning_upright_zh: '自我束缚，物质诱惑，恐惧和限制，需要打破枷锁。',
    meaning_upright_en: 'Self-bondage, material temptation, fear and limitation, need to break free.',
    meaning_reversed_zh: '摆脱束缚，克服恐惧，精神自由，摆脱物质主义。',
    meaning_reversed_en: 'Breaking free from bondage, overcoming fear, spiritual freedom, breaking free from materialism.',
    element: 'Earth',
    astrological_sign: 'Capricorn',
    planet: 'Saturn',
    description_zh: '恶魔象征着束缚和诱惑。他提醒我们要识别和打破自我束缚，克服恐惧，追求真正的自由。',
    description_en: 'The Devil symbolizes bondage and temptation. He reminds us to identify and break free from self-bondage, overcome fear, and pursue true freedom.'
  },
  {
    name_zh: '高塔',
    name_en: 'The Tower',
    suit: 'major',
    number: 16,
    image_url: '/images/tarot/major/tower.jpg',
    keywords_zh: '["突然变化", "启示", "解放", "重建"]',
    keywords_en: '["Sudden Change", "Revelation", "Liberation", "Rebuilding"]',
    meaning_upright_zh: '突然的变化，重要的启示，从束缚中解放，重建的机会。',
    meaning_upright_en: 'Sudden changes, important revelations, liberation from bondage, opportunity for rebuilding.',
    meaning_reversed_zh: '避免变化，拒绝启示，继续束缚，无法重建。',
    meaning_reversed_en: 'Avoiding changes, refusing revelations, continuing bondage, unable to rebuild.',
    element: 'Fire',
    astrological_sign: 'Mars',
    planet: 'Mars',
    description_zh: '高塔象征着突然的变化和启示。他提醒我们有时候需要破坏旧的结构，通过突然的变化来获得解放和重建的机会。',
    description_en: 'The Tower symbolizes sudden changes and revelations. He reminds us that sometimes we need to destroy old structures, gain liberation and rebuilding opportunities through sudden changes.'
  },
  {
    name_zh: '星星',
    name_en: 'The Star',
    suit: 'major',
    number: 17,
    image_url: '/images/tarot/major/star.jpg',
    keywords_zh: '["希望", "灵感", "指引", "精神连接"]',
    keywords_en: '["Hope", "Inspiration", "Guidance", "Spiritual Connection"]',
    meaning_upright_zh: '希望和灵感，精神指引，内心的平静，与宇宙的连接。',
    meaning_upright_en: 'Hope and inspiration, spiritual guidance, inner peace, connection with the universe.',
    meaning_reversed_zh: '失去希望，缺乏灵感，精神空虚，与宇宙失去连接。',
    meaning_reversed_en: 'Loss of hope, lack of inspiration, spiritual emptiness, loss of connection with the universe.',
    element: 'Air',
    astrological_sign: 'Aquarius',
    planet: 'Uranus',
    description_zh: '星星象征着希望和灵感。她提醒我们要保持希望，相信宇宙的指引，在黑暗中寻找光明。',
    description_en: 'The Star symbolizes hope and inspiration. She reminds us to maintain hope, trust in the universe\'s guidance, and find light in darkness.'
  },
  {
    name_zh: '月亮',
    name_en: 'The Moon',
    suit: 'major',
    number: 18,
    image_url: '/images/tarot/major/moon.jpg',
    keywords_zh: '["潜意识", "幻觉", "恐惧", "直觉"]',
    keywords_en: '["Subconscious", "Illusion", "Fear", "Intuition"]',
    meaning_upright_zh: '潜意识的探索，面对恐惧，直觉的指引，幻觉和现实。',
    meaning_upright_en: 'Exploration of subconscious, facing fears, intuitive guidance, illusion and reality.',
    meaning_reversed_zh: '逃避恐惧，拒绝直觉，被幻觉迷惑，无法面对现实。',
    meaning_reversed_en: 'Avoiding fears, refusing intuition, deceived by illusions, unable to face reality.',
    element: 'Water',
    astrological_sign: 'Pisces',
    planet: 'Neptune',
    description_zh: '月亮象征着潜意识和直觉。她提醒我们要探索潜意识，面对内心的恐惧，相信直觉的指引。',
    description_en: 'The Moon symbolizes the subconscious and intuition. She reminds us to explore the subconscious, face inner fears, and trust intuitive guidance.'
  },
  {
    name_zh: '太阳',
    name_en: 'The Sun',
    suit: 'major',
    number: 19,
    image_url: '/images/tarot/major/sun.jpg',
    keywords_zh: '["成功", "快乐", "活力", "成就"]',
    keywords_en: '["Success", "Happiness", "Vitality", "Achievement"]',
    meaning_upright_zh: '成功和快乐，充满活力，积极的态度，成就和满足。',
    meaning_upright_en: 'Success and happiness, full of vitality, positive attitude, achievement and satisfaction.',
    meaning_reversed_zh: '暂时的成功，过度的自信，缺乏活力，无法享受成就。',
    meaning_reversed_en: 'Temporary success, excessive confidence, lack of vitality, unable to enjoy achievements.',
    element: 'Fire',
    astrological_sign: 'Sun',
    planet: 'Sun',
    description_zh: '太阳象征着成功和快乐。他提醒我们要享受生活的美好，保持积极的态度，庆祝自己的成就。',
    description_en: 'The Sun symbolizes success and happiness. He reminds us to enjoy the beauty of life, maintain a positive attitude, and celebrate our achievements.'
  },
  {
    name_zh: '审判',
    name_en: 'Judgement',
    suit: 'major',
    number: 20,
    image_url: '/images/tarot/major/judgement.jpg',
    keywords_zh: '["重生", "觉醒", "宽恕", "新的开始"]',
    keywords_en: '["Rebirth", "Awakening", "Forgiveness", "New Beginning"]',
    meaning_upright_zh: '精神的重生，觉醒和启示，宽恕过去，新的开始。',
    meaning_upright_en: 'Spiritual rebirth, awakening and revelation, forgiveness of the past, new beginning.',
    meaning_reversed_zh: '拒绝改变，无法宽恕，缺乏觉醒，停滞不前。',
    meaning_reversed_en: 'Refusing to change, unable to forgive, lack of awakening, stagnation.',
    element: 'Fire',
    astrological_sign: 'Pluto',
    planet: 'Pluto',
    description_zh: '审判象征着重生和觉醒。他提醒我们要宽恕过去，接受新的开始，在精神上获得重生。',
    description_en: 'Judgement symbolizes rebirth and awakening. He reminds us to forgive the past, accept new beginnings, and achieve spiritual rebirth.'
  },
  {
    name_zh: '世界',
    name_en: 'The World',
    suit: 'major',
    number: 21,
    image_url: '/images/tarot/major/world.jpg',
    keywords_zh: '["完成", "成就", "圆满", "新的循环"]',
    keywords_en: '["Completion", "Achievement", "Fulfillment", "New Cycle"]',
    meaning_upright_zh: '目标的完成，重大的成就，圆满的结局，新的循环开始。',
    meaning_upright_en: 'Completion of goals, major achievements, fulfilling endings, beginning of new cycles.',
    meaning_reversed_zh: '未完成的目标，缺乏成就感，无法结束，拒绝新的开始。',
    meaning_reversed_en: 'Unfinished goals, lack of achievement, unable to end, refusing new beginnings.',
    element: 'Earth',
    astrological_sign: 'Saturn',
    planet: 'Saturn',
    description_zh: '世界象征着完成和成就。她提醒我们要庆祝自己的成就，享受圆满的结局，为新的循环做好准备。',
    description_en: 'The World symbolizes completion and achievement. She reminds us to celebrate our achievements, enjoy fulfilling endings, and prepare for new cycles.'
  }
];

// 转义SQL字符串
const escapeSqlString = (str: string): string => {
  return str.replace(/'/g, "''");
};

// 生成完整的塔罗牌数据
export const generateTarotCardsData = (): string => {
  const cards = majorArcanaCards.map((card, index) => {
    const id = card.name_en.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
    return `INSERT OR REPLACE INTO tarot_cards (id, name_zh, name_en, suit, number, image_url, keywords_zh, keywords_en, meaning_upright_zh, meaning_upright_en, meaning_reversed_zh, meaning_reversed_en, element, astrological_sign, planet, description_zh, description_en) VALUES ('${id}', '${escapeSqlString(card.name_zh)}', '${escapeSqlString(card.name_en)}', '${card.suit}', ${card.number}, '${card.image_url}', '${escapeSqlString(card.keywords_zh)}', '${escapeSqlString(card.keywords_en)}', '${escapeSqlString(card.meaning_upright_zh)}', '${escapeSqlString(card.meaning_upright_en)}', '${escapeSqlString(card.meaning_reversed_zh)}', '${escapeSqlString(card.meaning_reversed_en)}', '${card.element || ''}', '${card.astrological_sign || ''}', '${card.planet || ''}', '${escapeSqlString(card.description_zh)}', '${escapeSqlString(card.description_en)}');`;
  });

  return cards.join('\n');
};

// 导出数据
export { majorArcanaCards };
