INSERT OR IGNORE INTO psychology_question_options (id, question_id, option_text, option_value, option_score, option_description, order_index, is_correct) VALUES
('ls-q1-opt-1', 'love-style-category-q1', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q1-opt-2', 'love-style-category-q1', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q1-opt-3', 'love-style-category-q1', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q1-opt-4', 'love-style-category-q1', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q1-opt-5', 'love-style-category-q1', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q2-opt-1', 'love-style-category-q2', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q2-opt-2', 'love-style-category-q2', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q2-opt-3', 'love-style-category-q2', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q2-opt-4', 'love-style-category-q2', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q2-opt-5', 'love-style-category-q2', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q3-opt-1', 'love-style-category-q3', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q3-opt-2', 'love-style-category-q3', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q3-opt-3', 'love-style-category-q3', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q3-opt-4', 'love-style-category-q3', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q3-opt-5', 'love-style-category-q3', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q4-opt-1', 'love-style-category-q4', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q4-opt-2', 'love-style-category-q4', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q4-opt-3', 'love-style-category-q4', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q4-opt-4', 'love-style-category-q4', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q4-opt-5', 'love-style-category-q4', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q5-opt-1', 'love-style-category-q5', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q5-opt-2', 'love-style-category-q5', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q5-opt-3', 'love-style-category-q5', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q5-opt-4', 'love-style-category-q5', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q5-opt-5', 'love-style-category-q5', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q6-opt-1', 'love-style-category-q6', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q6-opt-2', 'love-style-category-q6', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q6-opt-3', 'love-style-category-q6', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q6-opt-4', 'love-style-category-q6', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q6-opt-5', 'love-style-category-q6', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q7-opt-1', 'love-style-category-q7', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q7-opt-2', 'love-style-category-q7', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q7-opt-3', 'love-style-category-q7', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q7-opt-4', 'love-style-category-q7', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q7-opt-5', 'love-style-category-q7', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q8-opt-1', 'love-style-category-q8', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q8-opt-2', 'love-style-category-q8', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q8-opt-3', 'love-style-category-q8', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q8-opt-4', 'love-style-category-q8', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q8-opt-5', 'love-style-category-q8', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q9-opt-1', 'love-style-category-q9', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q9-opt-2', 'love-style-category-q9', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q9-opt-3', 'love-style-category-q9', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q9-opt-4', 'love-style-category-q9', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q9-opt-5', 'love-style-category-q9', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q10-opt-1', 'love-style-category-q10', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q10-opt-2', 'love-style-category-q10', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q10-opt-3', 'love-style-category-q10', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q10-opt-4', 'love-style-category-q10', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q10-opt-5', 'love-style-category-q10', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q11-opt-1', 'love-style-category-q11', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q11-opt-2', 'love-style-category-q11', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q11-opt-3', 'love-style-category-q11', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q11-opt-4', 'love-style-category-q11', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q11-opt-5', 'love-style-category-q11', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q12-opt-1', 'love-style-category-q12', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q12-opt-2', 'love-style-category-q12', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q12-opt-3', 'love-style-category-q12', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q12-opt-4', 'love-style-category-q12', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q12-opt-5', 'love-style-category-q12', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q13-opt-1', 'love-style-category-q13', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q13-opt-2', 'love-style-category-q13', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q13-opt-3', 'love-style-category-q13', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q13-opt-4', 'love-style-category-q13', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q13-opt-5', 'love-style-category-q13', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q14-opt-1', 'love-style-category-q14', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q14-opt-2', 'love-style-category-q14', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q14-opt-3', 'love-style-category-q14', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q14-opt-4', 'love-style-category-q14', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q14-opt-5', 'love-style-category-q14', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q15-opt-1', 'love-style-category-q15', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q15-opt-2', 'love-style-category-q15', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q15-opt-3', 'love-style-category-q15', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q15-opt-4', 'love-style-category-q15', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q15-opt-5', 'love-style-category-q15', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q16-opt-1', 'love-style-category-q16', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q16-opt-2', 'love-style-category-q16', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q16-opt-3', 'love-style-category-q16', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q16-opt-4', 'love-style-category-q16', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q16-opt-5', 'love-style-category-q16', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q17-opt-1', 'love-style-category-q17', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q17-opt-2', 'love-style-category-q17', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q17-opt-3', 'love-style-category-q17', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q17-opt-4', 'love-style-category-q17', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q17-opt-5', 'love-style-category-q17', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q18-opt-1', 'love-style-category-q18', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q18-opt-2', 'love-style-category-q18', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q18-opt-3', 'love-style-category-q18', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q18-opt-4', 'love-style-category-q18', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q18-opt-5', 'love-style-category-q18', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q19-opt-1', 'love-style-category-q19', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q19-opt-2', 'love-style-category-q19', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q19-opt-3', 'love-style-category-q19', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q19-opt-4', 'love-style-category-q19', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q19-opt-5', 'love-style-category-q19', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q20-opt-1', 'love-style-category-q20', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q20-opt-2', 'love-style-category-q20', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q20-opt-3', 'love-style-category-q20', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q20-opt-4', 'love-style-category-q20', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q20-opt-5', 'love-style-category-q20', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q21-opt-1', 'love-style-category-q21', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q21-opt-2', 'love-style-category-q21', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q21-opt-3', 'love-style-category-q21', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q21-opt-4', 'love-style-category-q21', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q21-opt-5', 'love-style-category-q21', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q22-opt-1', 'love-style-category-q22', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q22-opt-2', 'love-style-category-q22', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q22-opt-3', 'love-style-category-q22', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q22-opt-4', 'love-style-category-q22', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q22-opt-5', 'love-style-category-q22', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q23-opt-1', 'love-style-category-q23', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q23-opt-2', 'love-style-category-q23', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q23-opt-3', 'love-style-category-q23', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q23-opt-4', 'love-style-category-q23', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q23-opt-5', 'love-style-category-q23', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q24-opt-1', 'love-style-category-q24', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q24-opt-2', 'love-style-category-q24', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q24-opt-3', 'love-style-category-q24', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q24-opt-4', 'love-style-category-q24', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q24-opt-5', 'love-style-category-q24', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q25-opt-1', 'love-style-category-q25', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q25-opt-2', 'love-style-category-q25', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q25-opt-3', 'love-style-category-q25', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q25-opt-4', 'love-style-category-q25', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q25-opt-5', 'love-style-category-q25', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q26-opt-1', 'love-style-category-q26', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q26-opt-2', 'love-style-category-q26', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q26-opt-3', 'love-style-category-q26', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q26-opt-4', 'love-style-category-q26', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q26-opt-5', 'love-style-category-q26', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q27-opt-1', 'love-style-category-q27', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q27-opt-2', 'love-style-category-q27', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q27-opt-3', 'love-style-category-q27', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q27-opt-4', 'love-style-category-q27', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q27-opt-5', 'love-style-category-q27', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q28-opt-1', 'love-style-category-q28', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q28-opt-2', 'love-style-category-q28', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q28-opt-3', 'love-style-category-q28', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q28-opt-4', 'love-style-category-q28', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q28-opt-5', 'love-style-category-q28', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q29-opt-1', 'love-style-category-q29', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q29-opt-2', 'love-style-category-q29', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q29-opt-3', 'love-style-category-q29', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q29-opt-4', 'love-style-category-q29', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q29-opt-5', 'love-style-category-q29', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ls-q30-opt-1', 'love-style-category-q30', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ls-q30-opt-2', 'love-style-category-q30', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ls-q30-opt-3', 'love-style-category-q30', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ls-q30-opt-4', 'love-style-category-q30', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ls-q30-opt-5', 'love-style-category-q30', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q1-opt-1', 'love-language-category-q1', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q1-opt-2', 'love-language-category-q1', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q1-opt-3', 'love-language-category-q1', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q1-opt-4', 'love-language-category-q1', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q1-opt-5', 'love-language-category-q1', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q2-opt-1', 'love-language-category-q2', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q2-opt-2', 'love-language-category-q2', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q2-opt-3', 'love-language-category-q2', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q2-opt-4', 'love-language-category-q2', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q2-opt-5', 'love-language-category-q2', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q3-opt-1', 'love-language-category-q3', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q3-opt-2', 'love-language-category-q3', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q3-opt-3', 'love-language-category-q3', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q3-opt-4', 'love-language-category-q3', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q3-opt-5', 'love-language-category-q3', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q4-opt-1', 'love-language-category-q4', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q4-opt-2', 'love-language-category-q4', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q4-opt-3', 'love-language-category-q4', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q4-opt-4', 'love-language-category-q4', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q4-opt-5', 'love-language-category-q4', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q5-opt-1', 'love-language-category-q5', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q5-opt-2', 'love-language-category-q5', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q5-opt-3', 'love-language-category-q5', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q5-opt-4', 'love-language-category-q5', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q5-opt-5', 'love-language-category-q5', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q6-opt-1', 'love-language-category-q6', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q6-opt-2', 'love-language-category-q6', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q6-opt-3', 'love-language-category-q6', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q6-opt-4', 'love-language-category-q6', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q6-opt-5', 'love-language-category-q6', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q7-opt-1', 'love-language-category-q7', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q7-opt-2', 'love-language-category-q7', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q7-opt-3', 'love-language-category-q7', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q7-opt-4', 'love-language-category-q7', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q7-opt-5', 'love-language-category-q7', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q8-opt-1', 'love-language-category-q8', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q8-opt-2', 'love-language-category-q8', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q8-opt-3', 'love-language-category-q8', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q8-opt-4', 'love-language-category-q8', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q8-opt-5', 'love-language-category-q8', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q9-opt-1', 'love-language-category-q9', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q9-opt-2', 'love-language-category-q9', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q9-opt-3', 'love-language-category-q9', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q9-opt-4', 'love-language-category-q9', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q9-opt-5', 'love-language-category-q9', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q10-opt-1', 'love-language-category-q10', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q10-opt-2', 'love-language-category-q10', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q10-opt-3', 'love-language-category-q10', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q10-opt-4', 'love-language-category-q10', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q10-opt-5', 'love-language-category-q10', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q11-opt-1', 'love-language-category-q11', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q11-opt-2', 'love-language-category-q11', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q11-opt-3', 'love-language-category-q11', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q11-opt-4', 'love-language-category-q11', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q11-opt-5', 'love-language-category-q11', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q12-opt-1', 'love-language-category-q12', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q12-opt-2', 'love-language-category-q12', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q12-opt-3', 'love-language-category-q12', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q12-opt-4', 'love-language-category-q12', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q12-opt-5', 'love-language-category-q12', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q13-opt-1', 'love-language-category-q13', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q13-opt-2', 'love-language-category-q13', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q13-opt-3', 'love-language-category-q13', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q13-opt-4', 'love-language-category-q13', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q13-opt-5', 'love-language-category-q13', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q14-opt-1', 'love-language-category-q14', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q14-opt-2', 'love-language-category-q14', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q14-opt-3', 'love-language-category-q14', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q14-opt-4', 'love-language-category-q14', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q14-opt-5', 'love-language-category-q14', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q15-opt-1', 'love-language-category-q15', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q15-opt-2', 'love-language-category-q15', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q15-opt-3', 'love-language-category-q15', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q15-opt-4', 'love-language-category-q15', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q15-opt-5', 'love-language-category-q15', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q16-opt-1', 'love-language-category-q16', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q16-opt-2', 'love-language-category-q16', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q16-opt-3', 'love-language-category-q16', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q16-opt-4', 'love-language-category-q16', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q16-opt-5', 'love-language-category-q16', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q17-opt-1', 'love-language-category-q17', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q17-opt-2', 'love-language-category-q17', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q17-opt-3', 'love-language-category-q17', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q17-opt-4', 'love-language-category-q17', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q17-opt-5', 'love-language-category-q17', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q18-opt-1', 'love-language-category-q18', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q18-opt-2', 'love-language-category-q18', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q18-opt-3', 'love-language-category-q18', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q18-opt-4', 'love-language-category-q18', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q18-opt-5', 'love-language-category-q18', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q19-opt-1', 'love-language-category-q19', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q19-opt-2', 'love-language-category-q19', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q19-opt-3', 'love-language-category-q19', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q19-opt-4', 'love-language-category-q19', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q19-opt-5', 'love-language-category-q19', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q20-opt-1', 'love-language-category-q20', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q20-opt-2', 'love-language-category-q20', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q20-opt-3', 'love-language-category-q20', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q20-opt-4', 'love-language-category-q20', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q20-opt-5', 'love-language-category-q20', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q21-opt-1', 'love-language-category-q21', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q21-opt-2', 'love-language-category-q21', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q21-opt-3', 'love-language-category-q21', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q21-opt-4', 'love-language-category-q21', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q21-opt-5', 'love-language-category-q21', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q22-opt-1', 'love-language-category-q22', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q22-opt-2', 'love-language-category-q22', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q22-opt-3', 'love-language-category-q22', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q22-opt-4', 'love-language-category-q22', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q22-opt-5', 'love-language-category-q22', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q23-opt-1', 'love-language-category-q23', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q23-opt-2', 'love-language-category-q23', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q23-opt-3', 'love-language-category-q23', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q23-opt-4', 'love-language-category-q23', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q23-opt-5', 'love-language-category-q23', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q24-opt-1', 'love-language-category-q24', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q24-opt-2', 'love-language-category-q24', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q24-opt-3', 'love-language-category-q24', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q24-opt-4', 'love-language-category-q24', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q24-opt-5', 'love-language-category-q24', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q25-opt-1', 'love-language-category-q25', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q25-opt-2', 'love-language-category-q25', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q25-opt-3', 'love-language-category-q25', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q25-opt-4', 'love-language-category-q25', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q25-opt-5', 'love-language-category-q25', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q26-opt-1', 'love-language-category-q26', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q26-opt-2', 'love-language-category-q26', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q26-opt-3', 'love-language-category-q26', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q26-opt-4', 'love-language-category-q26', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q26-opt-5', 'love-language-category-q26', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q27-opt-1', 'love-language-category-q27', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q27-opt-2', 'love-language-category-q27', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q27-opt-3', 'love-language-category-q27', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q27-opt-4', 'love-language-category-q27', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q27-opt-5', 'love-language-category-q27', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q28-opt-1', 'love-language-category-q28', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q28-opt-2', 'love-language-category-q28', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q28-opt-3', 'love-language-category-q28', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q28-opt-4', 'love-language-category-q28', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q28-opt-5', 'love-language-category-q28', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q29-opt-1', 'love-language-category-q29', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q29-opt-2', 'love-language-category-q29', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q29-opt-3', 'love-language-category-q29', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q29-opt-4', 'love-language-category-q29', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q29-opt-5', 'love-language-category-q29', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ll-q30-opt-1', 'love-language-category-q30', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ll-q30-opt-2', 'love-language-category-q30', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ll-q30-opt-3', 'love-language-category-q30', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ll-q30-opt-4', 'love-language-category-q30', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ll-q30-opt-5', 'love-language-category-q30', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q1-opt-1', 'interpersonal-category-q1', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q1-opt-2', 'interpersonal-category-q1', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q1-opt-3', 'interpersonal-category-q1', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q1-opt-4', 'interpersonal-category-q1', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q1-opt-5', 'interpersonal-category-q1', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q2-opt-1', 'interpersonal-category-q2', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q2-opt-2', 'interpersonal-category-q2', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q2-opt-3', 'interpersonal-category-q2', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q2-opt-4', 'interpersonal-category-q2', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q2-opt-5', 'interpersonal-category-q2', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q3-opt-1', 'interpersonal-category-q3', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q3-opt-2', 'interpersonal-category-q3', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q3-opt-3', 'interpersonal-category-q3', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q3-opt-4', 'interpersonal-category-q3', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q3-opt-5', 'interpersonal-category-q3', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q4-opt-1', 'interpersonal-category-q4', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q4-opt-2', 'interpersonal-category-q4', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q4-opt-3', 'interpersonal-category-q4', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q4-opt-4', 'interpersonal-category-q4', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q4-opt-5', 'interpersonal-category-q4', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q5-opt-1', 'interpersonal-category-q5', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q5-opt-2', 'interpersonal-category-q5', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q5-opt-3', 'interpersonal-category-q5', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q5-opt-4', 'interpersonal-category-q5', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q5-opt-5', 'interpersonal-category-q5', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q6-opt-1', 'interpersonal-category-q6', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q6-opt-2', 'interpersonal-category-q6', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q6-opt-3', 'interpersonal-category-q6', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q6-opt-4', 'interpersonal-category-q6', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q6-opt-5', 'interpersonal-category-q6', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q7-opt-1', 'interpersonal-category-q7', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q7-opt-2', 'interpersonal-category-q7', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q7-opt-3', 'interpersonal-category-q7', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q7-opt-4', 'interpersonal-category-q7', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q7-opt-5', 'interpersonal-category-q7', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q8-opt-1', 'interpersonal-category-q8', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q8-opt-2', 'interpersonal-category-q8', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q8-opt-3', 'interpersonal-category-q8', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q8-opt-4', 'interpersonal-category-q8', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q8-opt-5', 'interpersonal-category-q8', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q9-opt-1', 'interpersonal-category-q9', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q9-opt-2', 'interpersonal-category-q9', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q9-opt-3', 'interpersonal-category-q9', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q9-opt-4', 'interpersonal-category-q9', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q9-opt-5', 'interpersonal-category-q9', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q10-opt-1', 'interpersonal-category-q10', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q10-opt-2', 'interpersonal-category-q10', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q10-opt-3', 'interpersonal-category-q10', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q10-opt-4', 'interpersonal-category-q10', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q10-opt-5', 'interpersonal-category-q10', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q11-opt-1', 'interpersonal-category-q11', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q11-opt-2', 'interpersonal-category-q11', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q11-opt-3', 'interpersonal-category-q11', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q11-opt-4', 'interpersonal-category-q11', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q11-opt-5', 'interpersonal-category-q11', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q12-opt-1', 'interpersonal-category-q12', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q12-opt-2', 'interpersonal-category-q12', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q12-opt-3', 'interpersonal-category-q12', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q12-opt-4', 'interpersonal-category-q12', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q12-opt-5', 'interpersonal-category-q12', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q13-opt-1', 'interpersonal-category-q13', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q13-opt-2', 'interpersonal-category-q13', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q13-opt-3', 'interpersonal-category-q13', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q13-opt-4', 'interpersonal-category-q13', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q13-opt-5', 'interpersonal-category-q13', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q14-opt-1', 'interpersonal-category-q14', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q14-opt-2', 'interpersonal-category-q14', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q14-opt-3', 'interpersonal-category-q14', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q14-opt-4', 'interpersonal-category-q14', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q14-opt-5', 'interpersonal-category-q14', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q15-opt-1', 'interpersonal-category-q15', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q15-opt-2', 'interpersonal-category-q15', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q15-opt-3', 'interpersonal-category-q15', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q15-opt-4', 'interpersonal-category-q15', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q15-opt-5', 'interpersonal-category-q15', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q16-opt-1', 'interpersonal-category-q16', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q16-opt-2', 'interpersonal-category-q16', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q16-opt-3', 'interpersonal-category-q16', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q16-opt-4', 'interpersonal-category-q16', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q16-opt-5', 'interpersonal-category-q16', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q17-opt-1', 'interpersonal-category-q17', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q17-opt-2', 'interpersonal-category-q17', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q17-opt-3', 'interpersonal-category-q17', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q17-opt-4', 'interpersonal-category-q17', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q17-opt-5', 'interpersonal-category-q17', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q18-opt-1', 'interpersonal-category-q18', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q18-opt-2', 'interpersonal-category-q18', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q18-opt-3', 'interpersonal-category-q18', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q18-opt-4', 'interpersonal-category-q18', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q18-opt-5', 'interpersonal-category-q18', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q19-opt-1', 'interpersonal-category-q19', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q19-opt-2', 'interpersonal-category-q19', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q19-opt-3', 'interpersonal-category-q19', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q19-opt-4', 'interpersonal-category-q19', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q19-opt-5', 'interpersonal-category-q19', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q20-opt-1', 'interpersonal-category-q20', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q20-opt-2', 'interpersonal-category-q20', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q20-opt-3', 'interpersonal-category-q20', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q20-opt-4', 'interpersonal-category-q20', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q20-opt-5', 'interpersonal-category-q20', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q21-opt-1', 'interpersonal-category-q21', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q21-opt-2', 'interpersonal-category-q21', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q21-opt-3', 'interpersonal-category-q21', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q21-opt-4', 'interpersonal-category-q21', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q21-opt-5', 'interpersonal-category-q21', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q22-opt-1', 'interpersonal-category-q22', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q22-opt-2', 'interpersonal-category-q22', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q22-opt-3', 'interpersonal-category-q22', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q22-opt-4', 'interpersonal-category-q22', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q22-opt-5', 'interpersonal-category-q22', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q23-opt-1', 'interpersonal-category-q23', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q23-opt-2', 'interpersonal-category-q23', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q23-opt-3', 'interpersonal-category-q23', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q23-opt-4', 'interpersonal-category-q23', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q23-opt-5', 'interpersonal-category-q23', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q24-opt-1', 'interpersonal-category-q24', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q24-opt-2', 'interpersonal-category-q24', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q24-opt-3', 'interpersonal-category-q24', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q24-opt-4', 'interpersonal-category-q24', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q24-opt-5', 'interpersonal-category-q24', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q25-opt-1', 'interpersonal-category-q25', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q25-opt-2', 'interpersonal-category-q25', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q25-opt-3', 'interpersonal-category-q25', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q25-opt-4', 'interpersonal-category-q25', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q25-opt-5', 'interpersonal-category-q25', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q26-opt-1', 'interpersonal-category-q26', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q26-opt-2', 'interpersonal-category-q26', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q26-opt-3', 'interpersonal-category-q26', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q26-opt-4', 'interpersonal-category-q26', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q26-opt-5', 'interpersonal-category-q26', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q27-opt-1', 'interpersonal-category-q27', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q27-opt-2', 'interpersonal-category-q27', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q27-opt-3', 'interpersonal-category-q27', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q27-opt-4', 'interpersonal-category-q27', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q27-opt-5', 'interpersonal-category-q27', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q28-opt-1', 'interpersonal-category-q28', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q28-opt-2', 'interpersonal-category-q28', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q28-opt-3', 'interpersonal-category-q28', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q28-opt-4', 'interpersonal-category-q28', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q28-opt-5', 'interpersonal-category-q28', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q29-opt-1', 'interpersonal-category-q29', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q29-opt-2', 'interpersonal-category-q29', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q29-opt-3', 'interpersonal-category-q29', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q29-opt-4', 'interpersonal-category-q29', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q29-opt-5', 'interpersonal-category-q29', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0),
('ip-q30-opt-1', 'interpersonal-category-q30', 'Strongly Disagree', '1', 1, 'Completely does not match my situation', 1, 0),
('ip-q30-opt-2', 'interpersonal-category-q30', 'Disagree', '2', 2, 'Mostly does not match my situation', 2, 0),
('ip-q30-opt-3', 'interpersonal-category-q30', 'Neutral', '3', 3, 'Partially matches my situation', 3, 0),
('ip-q30-opt-4', 'interpersonal-category-q30', 'Agree', '4', 4, 'Mostly matches my situation', 4, 0),
('ip-q30-opt-5', 'interpersonal-category-q30', 'Strongly Agree', '5', 5, 'Completely matches my situation', 5, 0);
