-- Insert Love Language Test questions (30 questions)
INSERT OR IGNORE INTO psychology_questions (id, category_id, question_text, question_type, dimension, weight, order_index, is_required) VALUES
('love-language-category-q1', 'love-language-category', 'I feel most loved when someone tells me they love me.', 'likert_scale', 'Words_of_Affirmation', 1, 1, 1),
('love-language-category-q2', 'love-language-category', 'I appreciate when someone compliments me or says nice things about me.', 'likert_scale', 'Words_of_Affirmation', 1, 2, 1),
('love-language-category-q3', 'love-language-category', 'I value verbal encouragement and support from my partner.', 'likert_scale', 'Words_of_Affirmation', 1, 3, 1),
('love-language-category-q4', 'love-language-category', 'I feel hurt when someone criticizes me or says negative things.', 'likert_scale', 'Words_of_Affirmation', 1, 4, 1),
('love-language-category-q5', 'love-language-category', 'I appreciate when someone acknowledges my efforts and achievements.', 'likert_scale', 'Words_of_Affirmation', 1, 5, 1),
('love-language-category-q6', 'love-language-category', 'I feel most loved when someone spends quality time with me.', 'likert_scale', 'Quality_Time', 1, 6, 1),
('love-language-category-q7', 'love-language-category', 'I value undivided attention from my partner.', 'likert_scale', 'Quality_Time', 1, 7, 1),
('love-language-category-q8', 'love-language-category', 'I enjoy doing activities together with my partner.', 'likert_scale', 'Quality_Time', 1, 8, 1),
('love-language-category-q9', 'love-language-category', 'I feel hurt when someone is distracted or not present when we are together.', 'likert_scale', 'Quality_Time', 1, 9, 1),
('love-language-category-q10', 'love-language-category', 'I appreciate when someone makes time for me in their busy schedule.', 'likert_scale', 'Quality_Time', 1, 10, 1),
('love-language-category-q11', 'love-language-category', 'I feel most loved when someone gives me thoughtful gifts.', 'likert_scale', 'Receiving_Gifts', 1, 11, 1),
('love-language-category-q12', 'love-language-category', 'I appreciate when someone remembers special occasions with gifts.', 'likert_scale', 'Receiving_Gifts', 1, 12, 1),
('love-language-category-q13', 'love-language-category', 'I value the thought and effort behind gift-giving.', 'likert_scale', 'Receiving_Gifts', 1, 13, 1),
('love-language-category-q14', 'love-language-category', 'I feel hurt when someone forgets to give me a gift on special occasions.', 'likert_scale', 'Receiving_Gifts', 1, 14, 1),
('love-language-category-q15', 'love-language-category', 'I appreciate both big and small presents from my partner.', 'likert_scale', 'Receiving_Gifts', 1, 15, 1),
('love-language-category-q16', 'love-language-category', 'I feel most loved when someone helps me with tasks or chores.', 'likert_scale', 'Acts_of_Service', 1, 16, 1),
('love-language-category-q17', 'love-language-category', 'I appreciate when someone goes out of their way to help me.', 'likert_scale', 'Acts_of_Service', 1, 17, 1),
('love-language-category-q18', 'love-language-category', 'I feel valued when someone takes care of things for me.', 'likert_scale', 'Acts_of_Service', 1, 18, 1),
('love-language-category-q19', 'love-language-category', 'I notice and appreciate small acts of kindness and help.', 'likert_scale', 'Acts_of_Service', 1, 19, 1),
('love-language-category-q20', 'love-language-category', 'I feel hurt when someone refuses to help me when I need it.', 'likert_scale', 'Acts_of_Service', 1, 20, 1),
('love-language-category-q21', 'love-language-category', 'I feel most loved when someone shows me physical affection.', 'likert_scale', 'Physical_Touch', 1, 21, 1),
('love-language-category-q22', 'love-language-category', 'Hugs, kisses, and holding hands are important to me.', 'likert_scale', 'Physical_Touch', 1, 22, 1),
('love-language-category-q23', 'love-language-category', 'I feel connected to my partner through physical closeness.', 'likert_scale', 'Physical_Touch', 1, 23, 1),
('love-language-category-q24', 'love-language-category', 'I appreciate non-sexual physical contact and touch.', 'likert_scale', 'Physical_Touch', 1, 24, 1),
('love-language-category-q25', 'love-language-category', 'I feel hurt when someone avoids physical contact with me.', 'likert_scale', 'Physical_Touch', 1, 25, 1),
('love-language-category-q26', 'love-language-category', 'I value the warmth and comfort of physical touch in relationships.', 'likert_scale', 'Physical_Touch', 1, 26, 1),
('love-language-category-q27', 'love-language-category', 'I feel most loved when someone gives me their full attention.', 'likert_scale', 'Quality_Time', 1, 27, 1),
('love-language-category-q28', 'love-language-category', 'I appreciate when someone listens to me without interrupting.', 'likert_scale', 'Quality_Time', 1, 28, 1),
('love-language-category-q29', 'love-language-category', 'I feel most loved when someone writes me a heartfelt note or message.', 'likert_scale', 'Words_of_Affirmation', 1, 29, 1),
('love-language-category-q30', 'love-language-category', 'I appreciate when someone expresses their love for me in words.', 'likert_scale', 'Words_of_Affirmation', 1, 30, 1);
