-- Insert remaining Love Style Assessment questions (6-30)
INSERT OR IGNORE INTO psychology_questions (id, category_id, question_text, question_type, dimension, weight, order_index, is_required) VALUES
('love-style-category-q6', 'love-style-category', 'I enjoy the thrill of flirting and the early stages of dating.', 'likert_scale', 'Ludus', 1, 6, 1),
('love-style-category-q7', 'love-style-category', 'I see relationships as fun games to be played and enjoyed.', 'likert_scale', 'Ludus', 1, 7, 1),
('love-style-category-q8', 'love-style-category', 'I prefer to keep relationships light and avoid getting too serious too quickly.', 'likert_scale', 'Ludus', 1, 8, 1),
('love-style-category-q9', 'love-style-category', 'I enjoy dating multiple people and keeping my options open.', 'likert_scale', 'Ludus', 1, 9, 1),
('love-style-category-q10', 'love-style-category', 'I believe love should be fun and not taken too seriously.', 'likert_scale', 'Ludus', 1, 10, 1),
('love-style-category-q11', 'love-style-category', 'I prefer relationships that develop gradually from friendship.', 'likert_scale', 'Storge', 1, 11, 1),
('love-style-category-q12', 'love-style-category', 'I value companionship and shared interests in relationships.', 'likert_scale', 'Storge', 1, 12, 1),
('love-style-category-q13', 'love-style-category', 'I believe love grows over time through shared experiences.', 'likert_scale', 'Storge', 1, 13, 1),
('love-style-category-q14', 'love-style-category', 'I prefer stable, long-term relationships over passionate affairs.', 'likert_scale', 'Storge', 1, 14, 1),
('love-style-category-q15', 'love-style-category', 'I see love as a deep friendship that develops into something more.', 'likert_scale', 'Storge', 1, 15, 1),
('love-style-category-q16', 'love-style-category', 'I am practical and logical when choosing a partner.', 'likert_scale', 'Pragma', 1, 16, 1),
('love-style-category-q17', 'love-style-category', 'I consider compatibility and shared goals important in relationships.', 'likert_scale', 'Pragma', 1, 17, 1),
('love-style-category-q18', 'love-style-category', 'I make lists of qualities I want in a partner.', 'likert_scale', 'Pragma', 1, 18, 1),
('love-style-category-q19', 'love-style-category', 'I believe love should be based on mutual respect and understanding.', 'likert_scale', 'Pragma', 1, 19, 1),
('love-style-category-q20', 'love-style-category', 'I think carefully about the long-term potential of relationships.', 'likert_scale', 'Pragma', 1, 20, 1),
('love-style-category-q21', 'love-style-category', 'I become obsessive and possessive in relationships.', 'likert_scale', 'Mania', 1, 21, 1),
('love-style-category-q22', 'love-style-category', 'I experience extreme highs and lows in love.', 'likert_scale', 'Mania', 1, 22, 1),
('love-style-category-q23', 'love-style-category', 'I need constant reassurance from my partner.', 'likert_scale', 'Mania', 1, 23, 1),
('love-style-category-q24', 'love-style-category', 'I feel anxious when I am not with my partner.', 'likert_scale', 'Mania', 1, 24, 1),
('love-style-category-q25', 'love-style-category', 'I have difficulty trusting my partner completely.', 'likert_scale', 'Mania', 1, 25, 1),
('love-style-category-q26', 'love-style-category', 'I believe in unconditional love and acceptance.', 'likert_scale', 'Agape', 1, 26, 1),
('love-style-category-q27', 'love-style-category', 'I put my partner''s needs before my own.', 'likert_scale', 'Agape', 1, 27, 1),
('love-style-category-q28', 'love-style-category', 'I believe love should be selfless and giving.', 'likert_scale', 'Agape', 1, 28, 1),
('love-style-category-q29', 'love-style-category', 'I am willing to sacrifice for the person I love.', 'likert_scale', 'Agape', 1, 29, 1),
('love-style-category-q30', 'love-style-category', 'I believe love should be unconditional and everlasting.', 'likert_scale', 'Agape', 1, 30, 1);
