-- Insert Interpersonal Skills Assessment questions (30 questions)
INSERT OR IGNORE INTO psychology_questions (id, category_id, question_text, question_type, dimension, weight, order_index, is_required) VALUES
('interpersonal-category-q1', 'interpersonal-category', 'I can clearly express my thoughts and feelings to others.', 'likert_scale', 'Communication_Skills', 1, 1, 1),
('interpersonal-category-q2', 'interpersonal-category', 'I actively listen when others are speaking to me.', 'likert_scale', 'Communication_Skills', 1, 2, 1),
('interpersonal-category-q3', 'interpersonal-category', 'I can ask clarifying questions when I don''t understand something.', 'likert_scale', 'Communication_Skills', 1, 3, 1),
('interpersonal-category-q4', 'interpersonal-category', 'I can provide constructive feedback to others.', 'likert_scale', 'Communication_Skills', 1, 4, 1),
('interpersonal-category-q5', 'interpersonal-category', 'I can adapt my communication style to different situations.', 'likert_scale', 'Communication_Skills', 1, 5, 1),
('interpersonal-category-q6', 'interpersonal-category', 'I can communicate effectively in both one-on-one and group settings.', 'likert_scale', 'Communication_Skills', 1, 6, 1),
('interpersonal-category-q7', 'interpersonal-category', 'I can understand and share the feelings of others.', 'likert_scale', 'Empathy', 1, 7, 1),
('interpersonal-category-q8', 'interpersonal-category', 'I can see situations from another person''s perspective.', 'likert_scale', 'Empathy', 1, 8, 1),
('interpersonal-category-q9', 'interpersonal-category', 'I can recognize when someone needs emotional support.', 'likert_scale', 'Empathy', 1, 9, 1),
('interpersonal-category-q10', 'interpersonal-category', 'I can respond appropriately to others'' emotional states.', 'likert_scale', 'Empathy', 1, 10, 1),
('interpersonal-category-q11', 'interpersonal-category', 'I can show compassion towards others in difficult situations.', 'likert_scale', 'Empathy', 1, 11, 1),
('interpersonal-category-q12', 'interpersonal-category', 'I can validate others'' feelings without judgment.', 'likert_scale', 'Empathy', 1, 12, 1),
('interpersonal-category-q13', 'interpersonal-category', 'I can stay calm during disagreements with others.', 'likert_scale', 'Conflict_Resolution', 1, 13, 1),
('interpersonal-category-q14', 'interpersonal-category', 'I can find common ground with people who have different opinions.', 'likert_scale', 'Conflict_Resolution', 1, 14, 1),
('interpersonal-category-q15', 'interpersonal-category', 'I can compromise when necessary to resolve conflicts.', 'likert_scale', 'Conflict_Resolution', 1, 15, 1),
('interpersonal-category-q16', 'interpersonal-category', 'I can address conflicts directly rather than avoiding them.', 'likert_scale', 'Conflict_Resolution', 1, 16, 1),
('interpersonal-category-q17', 'interpersonal-category', 'I can separate the person from the problem during conflicts.', 'likert_scale', 'Conflict_Resolution', 1, 17, 1),
('interpersonal-category-q18', 'interpersonal-category', 'I can work towards win-win solutions in conflicts.', 'likert_scale', 'Conflict_Resolution', 1, 18, 1),
('interpersonal-category-q19', 'interpersonal-category', 'I can build trust through consistent and reliable behavior.', 'likert_scale', 'Trust_Building', 1, 19, 1),
('interpersonal-category-q20', 'interpersonal-category', 'I can keep confidential information private.', 'likert_scale', 'Trust_Building', 1, 20, 1),
('interpersonal-category-q21', 'interpersonal-category', 'I can admit when I make mistakes.', 'likert_scale', 'Trust_Building', 1, 21, 1),
('interpersonal-category-q22', 'interpersonal-category', 'I can follow through on my commitments to others.', 'likert_scale', 'Trust_Building', 1, 22, 1),
('interpersonal-category-q23', 'interpersonal-category', 'I can be honest even when it''s difficult.', 'likert_scale', 'Trust_Building', 1, 23, 1),
('interpersonal-category-q24', 'interpersonal-category', 'I can show vulnerability when appropriate.', 'likert_scale', 'Trust_Building', 1, 24, 1),
('interpersonal-category-q25', 'interpersonal-category', 'I can easily start conversations with new people.', 'likert_scale', 'Social_Skills', 1, 25, 1),
('interpersonal-category-q26', 'interpersonal-category', 'I can read social cues and adjust my behavior accordingly.', 'likert_scale', 'Social_Skills', 1, 26, 1),
('interpersonal-category-q27', 'interpersonal-category', 'I can work effectively in group settings.', 'likert_scale', 'Social_Skills', 1, 27, 1),
('interpersonal-category-q28', 'interpersonal-category', 'I can build and maintain friendships with different types of people.', 'likert_scale', 'Social_Skills', 1, 28, 1),
('interpersonal-category-q29', 'interpersonal-category', 'I can adapt my communication style to different audiences.', 'likert_scale', 'Social_Skills', 1, 29, 1),
('interpersonal-category-q30', 'interpersonal-category', 'I can navigate social situations with confidence and ease.', 'likert_scale', 'Social_Skills', 1, 30, 1);
