name = "selfatlas-backend-dev"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 本地D1数据库配置
[[d1_databases]]
binding = "DB"
database_name = "selfatlas-local"
database_id = "a9f563cf-ce1b-46f8-adfe-38d58c7686a0"

# 开发环境简化配置
[env.development]
name = "selfatlas-backend-dev"
route = "dev-api.selfatlas.net/*"

# 开发环境变量
[env.development.vars]
NODE_ENV = "development"
LOG_LEVEL = "debug"
ENABLE_ANALYTICS = "false"
ENABLE_CACHE = "false"
CACHE_TTL = "300"
MAX_REQUEST_SIZE = "2097152"
RATE_LIMIT_WINDOW = "60000"
RATE_LIMIT_MAX = "1000"

# 开发环境构建配置
[build]
command = "echo 'Skipping build for development'"
watch_dir = "src"
