name = "selfatlas-backend-local"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 本地D1数据库配置
[[d1_databases]]
binding = "DB"
database_name = "selfatlas-local"
database_id = "a9f563cf-ce1b-46f8-adfe-38d58c7686a0"
